export const data = [
  {
    number: '1',
    title: '가',
    type: '그룹',
    numberOfPeople: '3',
    time: '2',
    teacher: '한석원',
    date: '2021-07-23',
    id: '1',
  },
  {
    number: '2',
    title: '나',
    type: '그룹',
    numberOfPeople: '3',
    time: '2',
    teacher: '한석원',
    date: '2021-07-23',
    id: '2',
  },
  {
    number: '3',
    title: '다',
    type: '개인',
    numberOfPeople: '3',
    time: '2',
    teacher: '한석원',
    date: '2021-07-23',
    id: '3',
  },
  {
    number: '4',
    title: '제목입니다',
    type: '그룹',
    numberOfPeople: '3',
    time: '2',
    teacher: '배성현',
    date: '2021-07-23',
    id: '4',
  },
  {
    number: '5',
    title: '제목입니다',
    type: '그룹',
    numberOfPeople: '3',
    time: '2',
    teacher: '전병민',
    date: '2021-07-23',
    id: '5',
  },
  {
    number: '6',
    title: '제목입니다',
    type: '그룹',
    numberOfPeople: '3',
    time: '2',
    teacher: '한석원',
    date: '2021-07-23',
    id: '6',
  },
];
export const importantInfo = [
  {
    number: '공지',
    title: '가',
    type: '그룹',
    numberOfPeople: '3',
    time: '2',
    teacher: '한석원',
    date: '2021-07-23',
    id: '7',
  },
  {
    number: '공지',
    title: '나',
    type: '그룹',
    numberOfPeople: '3',
    time: '2',
    teacher: '한석원',
    date: '2021-07-23',
    id: '8',
  },
];
